In [4]:
import numpy as ns
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
#Read file from from path location
df = pd.read_csv('football_mini.csv')

In [6]:
#Have a view of dataset few lines
print(df.head())

   Unnamed: 0               Name  Age Nationality                 Club  \
0           0           L. Messi   31   Argentina         FC Barcelona
1           1  Cristiano Ronaldo   33    Portugal             Juventus
2           2          Neymar Jr   26      Brazil  Paris Saint-Germain
3           3             De Gea   27       Spain    Manchester United
4           4       K. De Bruyne   27     Belgium      Manchester City

       Value    Wage Position  Crossing  Finishing  ...  Penalties  Composure  \
0  110500000  565000       RF        84         95  ...         75         96
1   77000000  405000       ST        84         94  ...         85         95
2  118500000  290000       LW        79         87  ...         81         94
3   72000000  260000       GK        17         13  ...         40         68
4  102000000  355000      RCM        93         82  ...         79         88

   Marking  StandingTackle  SlidingTackle  GKDiving  GKHandling  GKKicking  \
0       33              28             26         6          11         15
1       28              31             23         7          11         15
2       27              24             33         9           9         15
3       15              21             13        90          85         87
4       68              58             51        15          13          5

   GKPositioning  GKReflexes
0             14           8
1             14          11
2             15          11
3             88          94
4             10          13

[5 rows x 42 columns]

In [4]:
print(df.isnull().sum())

Unnamed: 0         0
Name               0
Age                0
Nationality        0
Club               0
Value              0
Wage               0
Position           0
Crossing           0
Finishing          0
HeadingAccuracy    0
ShortPassing       0
Volleys            0
Dribbling          0
Curve              0
FKAccuracy         0
LongPassing        0
BallControl        0
Acceleration       0
SprintSpeed        0
Agility            0
Reactions          0
Balance            0
ShotPower          0
Jumping            0
Stamina            0
Strength           0
LongShots          0
Aggression         0
Interceptions      0
Positioning        0
Vision             0
Penalties          0
Composure          0
Marking            0
StandingTackle     0
SlidingTackle      0
GKDiving           0
GKHandling         0
GKKicking          0
GKPositioning      0
GKReflexes         0
dtype: int64

In [5]:
df.describe()

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,100.000000,100.000000,1.000000e+02,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000
mean,49.500000,27.950000,5.158500e+07,195960.000000,65.350000,64.780000,63.980000,77.23000,63.840000,72.970000,...,63.980000,82.380000,57.630000,55.130000,51.230000,19.280000,18.960000,18.510000,19.230000,19.38000
std,29.011492,3.273323,1.962104e+07,94888.762094,23.101609,25.636771,22.595691,15.25067,24.016711,23.017541,...,18.806285,6.675418,24.567637,27.602392,27.635746,25.424509,24.765535,23.029404,25.061482,26.06045
min,0.000000,19.000000,4.000000e+06,21000.000000,11.000000,10.000000,10.000000,29.00000,11.000000,10.000000,...,11.000000,65.000000,13.000000,10.000000,8.000000,2.000000,2.000000,2.000000,2.000000,3.00000
25%,24.750000,26.000000,3.750000e+07,125000.000000,57.750000,51.750000,54.000000,77.00000,52.750000,67.500000,...,57.500000,80.000000,34.000000,31.000000,25.000000,7.000000,8.000000,7.000000,7.000000,7.75000
50%,49.500000,28.000000,4.825000e+07,182500.000000,74.000000,74.000000,73.000000,82.00000,73.000000,81.500000,...,69.000000,83.000000,59.000000,54.500000,47.500000,11.000000,11.000000,11.500000,11.000000,10.00000
75%,74.250000,30.250000,6.212500e+07,240000.000000,82.000000,84.000000,82.000000,85.25000,81.250000,88.000000,...,78.000000,86.000000,80.250000,84.250000,80.000000,14.250000,14.000000,14.250000,14.250000,14.00000
max,99.000000,40.000000,1.185000e+08,565000.000000,93.000000,95.000000,92.000000,93.00000,90.000000,97.000000,...,90.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.00000

In [ ]:
#Plot of a histogram with players age
plt.figure(figsize=(7, 5))
plt.hist(df['Age'], bins=10, color='green', edgecolor='black', alpha=0.7)
#Axes labels and title
plt.title('Histogram of Players Ages', color='blue', fontsize=12, fontweight='bold')
plt.xlabel('Age Value')
plt.ylabel('Freqeuncy')
#saving the histogram image
plt.savefig('histogram of Players Age', dpi=96)
plt.show()

In [ ]:
#scatter plot of players Age and the thier finishig 
plt.figure(figsize=(6, 4))
plt.scatter(df['Age'], df['Finishing'], color='green', 
            edgecolor='green', alpha=0.7)
#Title and axes labeling with customizing
plt.xlabel('Age', color='black', fontweight='bold')
plt.title('Age vs Finishing', color='blue', fontsize=12, fontweight='bold' )
plt.ylabel('Finishing in %', color='black', fontsize=12, fontweight='bold')
#saving my image
plt.savefig('Age vs Finishing', dpi=96)
plt.show()

In [ ]:
    # Boxplot plot of comparism of player abilities 
    plt.figure(figsize=(6, 4))
    plt.boxplot([df['Finishing'], df['Crossing'], df['Curve'], df['Dribbling']])
    #lable of x and y axis 
    x=[1, 2, 3, 4,]
    lables=['Fininshing', 'Crossing', 'Curve', 'Dribbling']
    plt.xticks(x, lables)
    plt.title('Players Abilities', color='blue', fontweight='bold')
    plt.ylabel('Effeciency in %', fontweight='bold')
    #saving Players Abilities image
    plt.savefig('Players Abilities', dpi=96)
    plt.show()